---
abstract: 'Dancer 2 session storage with Cache::Memcached'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Dancer2: 0
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0.22
  HTTP::Date: 0
  JSON: 0
  LWP::UserAgent: 0
  List::Util: 0
  Test::More: 0
  Test::TCP: 1.13
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.130880'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer2-Session-Memcached
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Dancer2::Session::Memcached:
    file: lib/Dancer2/Session/Memcached.pm
    version: 0.003
requires:
  Cache::Memcached: 0
  Carp: 0
  Dancer2: 0.03
  Dancer2::Core::Role::SessionFactory: 0
  Dancer2::Core::Types: 0
  Moo: 0
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/dancer2-session-memcached/issues
  homepage: https://metacpan.org/release/Dancer2-Session-Memcached
  repository: git://github.com/dagolden/dancer2-session-memcached.git
version: 0.003
